[project]
name = "shared"
version = "0.1.0"
description = "Common shared code for lambdas"
authors = [{ name = "Rehan Haider" }]
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["shared"]
